name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release


jobs:
build:
  - uses: lukka/get-cmake@latest

  - name: Setup vcpkg
    uses: lukka/run-vcpkg@v11

  - name: Build with CMake
    uses: lukka/run-cmake@v10
    with:
      configurePreset: 'ninja-multi-vcpkg'
      buildPreset: 'ninja-multi-vcpkg'